### ISSUE TITLE
[Suggestion need] How to improve performance with image src?

### ISSUE THREAD

**Issue by wdkwyf** [dlstreamer/dlstreamer#335]
Hi, I want to use DL Streamer to inference single image, but find the performance is slow for GPU. Performance:
CPU: Intel(R) Xeon(R) Gold 6336Y 1.5 fps
GPU: ATS-M3 0.2 fps
My pipeline is as the following:
```
 PIPELINE="filesrc location=%s name=file : decodebin : videoconvert ! " % (join(args.input,file))
    CLASSIFY_1 = "gvaclassify model-instance-id=in0 model=customer_int8.xml model-proc=./model_proc/mask.json device=%s inference-region=0 pre-process-backend=opencv ! queue ! " %device
    CLASSIFY_2 = "gvaclassify model-instance-id=in1 model=age-gender-recognition-retail-0013.xml model-proc=model_proc/age-gender-recognition-retail-0013.json device=%s inference-region=0 pre-process-backend=opencv ! queue !" %device
    CLASSIFY_3 = "gvaclassify model-instance-id=in2 model=person-attributes-recognition-crossroad-0234.xml model-proc=model_proc/person-attributes-recognition-crossroad-0234.json device=%s inference-region=0 pre-process-backend=opencv ! queue !" %device
    SINK_ELEMENT="gvametaconvert ! gvametapublish file-format=json-lines file-path=output.json ! gvafpscounter ! fakesink async=false "
```
After processing a single image, I use the EOS signal to process the next image:
```
 if t == Gst.MessageType.EOS:
        print("pipeline ended, new image is:",end=""),
        pipeline.set_state(Gst.State.READY)
        filesrc = pipeline.get_by_name("file")
        filesrc.set_property('location',join(args.input,f))
        print(f)
        pipeline.set_state(Gst.State.PLAYING)
```

Not sure which parts (format, load_device time, memory copy?) lead to the low GPU performance, could you please give some advice? Thanks very much!

**Comment by brmarkus** [comment]
Can you provide more details about your environment, please?
Which OperatingSystem are you running on?

Which version of DL-Streamer and OpenVINO are you using?
How have you installed the drivers&packages for ATS-M3, in which version?

Do you use DL-Streamer "natively" in the OS or e.g. within a Docker container?

Have you retrieved&downloaded the models using the same version of OpenVINO than using with DL-Streamer?

When you use CPU instead of GPU, do you get the expected throughput ("performance"), just for consistency-check of the OS-installation?

When still using GPU, can you test the three models one-by-one first? Do all single models behave the same? (are you sure you want to use an INT8-quantized model with ATS-M3?)

Do you have a chance on checking with OpenVINO, first, by using e.g. "benchmark_app" for each model?

Can you make sure you start with a clean model-cache?

**Comment by wdkwyf** [comment]
Hi, thanks for your reply. @brmarkus .
I also test these 3 models in benchmark_app -api sync with the same openvino version used by dl streamer. (all environments are the same)
- classify_1: 0.5 ms
- classify_2: 1.39 ms
- classify_3: 1.51 ms
You can see from the above results that latencies are small enough, much shorter than DL Streamer latency.

**Comment by brmarkus** [comment]
Do you focus on latency (your values shown as e.g. "1.39ms) or throughput (your values shown as 0.2 fps)?

Can you describe your use-case first? What is the pipeline supposed to do?
Are you sure you want to use 3 classifications (and not some of them being e.g. object-detections), are you sure about the inference-region?
(like doing a face-detection first resulting in a small RegionOfInterest around the detected face, and then doing classification on the small face-ROI to determine age&gener, i.e. the steps are in a sequence and not in parallel, i.e. processing much less data due to previous "filtering")

**Comment by pk1d3v** [comment]
Hi @wdkwyf,

I see you are using `pre-process-backend=opencv`, it's CPU based and may be a bit slow. Also, you pipeline has CPU to GPU copy, which is slow operation as well. So you are spending a lot of time for pre-processing on CPU and copying data to GPU.

For optimal performance on GPU I'd suggest to use decoding on GPU `decodebin ! "video/x-raw(memory:VASurface)"` and pre-processing on GPU, avoiding CPU-GPU data copy by using `pre-process-backend=vaapi-surface-sharing`.

If you want to process multiple images at a time, probably `multifilesrc` would be better. Because sending EOS and re-initializing pipeline takes time as well. Also, please consider `appsrc`, may be it would fit better for your scenario.

**Comment by pk1d3v** [comment]
@wdkwyf, did this solve your problem? Вo you still need help with this?

**Comment by akwrobel** [comment]
Closed due to age and no response from submitter.
