### ISSUE TITLE
Failed to run pipeline on Arc A770

### ISSUE THREAD

**Issue by zhuo-yoyowz** [dlstreamer/dlstreamer#369]
I successfully installed and built Intel® DL Streamer Pipeline Framework. However, failed to run the pipeline with my Arc A770 dGPU with the following error:

** (gst-launch-1.0:19123): CRITICAL **: 16:32:52.818: GstStateChangeReturn MetaOverlayBinPrivate::change_state(GstStateChange): assertion 'link_elements()' failed
Failed to set pipeline to PAUSED.
Setting pipeline to NULL ...
Freeing pipeline ...

The command I used is:
gst-launch-1.0 filesrc location=pexels_1721294.mp4 ! decodebin ! video/x-raw\(memory:VASurface\) ! \
               gvadetect model=./models/yolov8n.xml \
                         model-proc=../samples/gstreamer/model_proc/public/yolo-v8.json \
                         pre-process-backend=vaapi-surface-sharing \
                         device=GPU ! \
                         meta_overlay device=GPU ! \
               videoconvert ! ximagesink

**Comment by brmarkus** [comment]
Can you provide more details about your environment - HW and SW, please?
Do you only have this one dGPU in the system?

What would be the simplified variant of the gst pipeline still working?
Is the video decoded on CPU or on GPU? Is decoding-only and rendering working?
Is it working when you ommit the `meta_overlay`?

**Comment by zhuo-yoyowz** [comment]
When I omitted "meta_overlay", here's what I've got

Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'vaapipostproc0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayWayland\)\ vaapidisplaywayland0", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayWayland\)\ vaapidisplaywayland0";
Redistribute latency...
WARNING: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0: Delayed linking failed.
Additional debug info:
gst/parse/grammar.y(540): gst_parse_no_more_pads (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0:
failed delayed linking some pad of GstDecodeBin named decodebin0 to some pad of GstGvaDetect named gvadetect0
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0: Internal data stream error.
Additional debug info:
../gst/isomp4/qtdemux.c(6749): gst_qtdemux_loop (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0:
streaming stopped, reason not-linked (-1)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstVaapiDecodeBin:vaapidecodebin0/GstQueue:queue0: Internal data stream error.
Additional debug info:
../plugins/elements/gstqueue.c(992): gst_queue_handle_sink_event (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstVaapiDecodeBin:vaapidecodebin0/GstQueue:queue0:
streaming stopped, reason not-linked (-1)
ERROR: pipeline doesn't want to preroll.
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference failed on stop
Additional debug info:
/home/zhuo/intel/dlstreamer_gst/gst/inference_elements/base/gva_base_inference.cpp(897): gva_base_inference_stop (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:
empty inference instance
ERROR: pipeline doesn't want to preroll.
Freeing pipeline ...

**Comment by zhuo-yoyowz** [comment]
For the HW and SW of my machine, I use Ubuntu 22.04
I have to GPUs, one is iGPU, the other one is Arc A770
I could observe D128 and D129 in -/dev/dri/ folder

**Comment by brmarkus** [comment]
The messages around `GstQTDemux:qtdemux0: Internal data stream error` could indicate a problem of the de-multiplexer to extract the embedded audio and video stream(s).

Are you able to use a simple pipeline to only decode (and render) the video?
Or could you try to use a different video file?

Messages around `GstVaapiDisplayWayland)\ vaapidisplaywayland0` look strange... because your given pipeline contains `ximagesink` (X/X11/x-server, instead of Wayland); you might want to try `autovideosink` (instead of `ximagesink`).

When there are two GPUs in your system (and you have the corresponding drivers installed), then OpenVINO wants and need to differentiate them, like `device=GPU.0` or `device=GPU.1` (like mentioned here: "https://docs.openvino.ai/2023.0/openvino_docs_OV_UG_supported_plugins_GPU.html").

Do you have an OpenVINO installation working in your environment, and could try to call the OpenVINO sample `./hello_query_device` (as mentioned under "https://docs.openvino.ai/2023.0/openvino_docs_OV_UG_supported_plugins_GPU.html")?

**Comment by pk1d3v** [comment]
In addition to @brmarkus comment:

Try to simplify pipeline as:
`gst-launch-1.0 filesrc location=pexels_1721294.mp4 ! decodebin ! video/x-raw(memory:VASurface) !
gvadetect model=./models/yolov8n.xml
model-proc=../samples/gstreamer/model_proc/public/yolo-v8.json
pre-process-backend=vaapi-surface-sharing
device=GPU ! fakesink`

Also, try to set environment variable: `GST_DEBUG=3`

**Comment by akwrobel** [comment]
Issue closed, no response on status from submitter.
