### ISSUE TITLE
Unable to run the pipeline using opencv videowriter

### ISSUE THREAD

**Issue by smohammad-de** [dlstreamer/dlstreamer#375]
I have this code, 

int main(int argc, char **argv)
{

  cv::Mat imReference = cv::imread("/home/intel-nuc1/pcb_image.png");
  cv::VideoCapture cap("v4l2src device=/dev/video0 ! decodebin ! videoconvert ! appsink",cv::CAP_GSTREAMER);
  if (!cap.isOpened()) {
        printf("=ERR= can't create video capture\n");
        return -1;
  }
  cv::VideoWriter writer;
 writer.open("appsrc ! videoconvert ! gvapython module=missing_components_roi4.py ! gvaclassify inference-region=1 model=d01_saved_model.xml  model_proc=D-01.json  device=CPU object-class=\"4\" ! gvawatermark ! fpsdisplaysink sync=false ", 0, 30, cv::Size(1920, 1080), true);
  if (!writer.isOpened()) {
    printf("=ERR= can't create video writer\n");
    return -1;
  }
  cv::Mat aligned, H;
  cv::Mat frame;
  int key;

  while (true) {
    cap >> frame;
    if (frame.empty())
        break;
    writer << frame;
    }
    cap.release();
    cv::destroyAllWindows();
    writer.release();
    return 0;
}

Here , missing_components_roi4.py is ,

import sys
import gi
gi.require_version('Gst', '1.0')
from gi.repository import Gst, GObject
from gstgva import VideoFrame
THRESHOLD = 0.5
Gst.init(sys.argv)
def process_frame(frame: VideoFrame, threshold: float = THRESHOLD) -> bool:
    roi = frame.add_region(1107.239263803681, 338.4355828220859, 70.67484662576703, 83.43558282208596,str("8"),1.0)
    return True
    
using terminal, the pipeline is working fine but not using cpp code.

Help would be appreciated !!

**Comment by brmarkus** [comment]
Can you provide more details, please?
What does "not working" mean, what does it look like?

What result(s) do you actually get, what should it look like?

Have you tried to look into the gstreamer logs (your C++ application) via OpenCV?
It might just be not found libraries or files (like due to current working dir; gstreamer plugin libs, Python script; ENV variables for e.g. GPU-accelerated libva-based codec).

Have you tried to narrow it down, piece by piece?

Some ideas:

Start with a simple decoding pipeline and video-writer pipeline - is OpenCV able to find the proper decoder and encoder plugins?
Would the decoder-pipeline with simpliest OpenVINO (just an inference or object-detection, based on the many demos and samples) work?

Could you try using `gvaclassify` with a region (like full frame) instead of going through the Python script first?
Would the decoding pipeline with integrated detection/inference/classification (instead of within the video-writer-pipeline) work?

**Comment by akwrobel** [comment]
Closing as there has been no response from the submitter on the requested configuration and reproduction information.
