### ISSUE TITLE
video/x-raw,: No such file or directory

### ISSUE THREAD

**Issue by henry8248** [dlstreamer/dlstreamer#388]
Hi. 
I've installed dlstreamer through option1 in this [guide](https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#id3). After the installation, I tried gst-launch-1.0 videotestsrc ! autovideosink, which functioned well. 
However, when I connected a webcam to read raw images, it kept saying "video/x-raw,: No such file or directory".

The pipeline I use: "gst-launch-1.0 -v v4l2src device=/dev/video2 io-mode=2 ! 
video/x-raw, format=NV12, width=1280, height=720 ! videoflip method=4 ! autovideosink" since my webcam supports NV12 format.
![Screenshot from 2023-11-16 11-20-54](https://github.com/dlstreamer/dlstreamer/assets/105163341/7b8cd97d-bf3f-4071-a0b5-bd0b878f0e95)

**I have tried 
>export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib .
>I've also tried option3(build it by cmake) but got this error message after entering "cmake .." in build directory
![Screenshot from 2023-11-16 11-47-38](https://github.com/dlstreamer/dlstreamer/assets/105163341/5f1acabd-cdb3-4555-9819-5da31cc61b6c)
**My OS: Ubuntu22.04
**Openvino: openvino_2023

Thanks for your help

**Comment by brmarkus** [comment]
Your GST command line indeed has a syntax error - when looking from a shell command line perspective.

Just put quotes (single or double quores) around the format specifier:

`"video/x-raw, format=NV12, width=1280, `height=720"`

or

`'video/x-raw, format=NV12, width=1280, height=720'`

(I haven't tried your command line due to lack of a raw-mode camera)

For building DL-Streamer - have you installed OpenVINO and called source `/opt/intel/openvino_2021/bin/setupvars.sh` (see also "https://docs.openvino.ai/2023.1/openvino_docs_install_guides_installing_openvino_from_archive_linux.html#step-2-configure-the-environment") - you would need to install the full development version, not just the runtime; otherwise CMake and compiler/linker won't find the needed resources.

**Comment by henry8248** [comment]
Hi brmarkus.
Sorry for the late reply! It was indeed a typo in my gst command line. Thanks! I have downloaded the archive file shown in **figure1** by following the installation guide shown in **figure2**  and called source /opt/intel/openvino_2021/bin/setupvars.sh successfully (It said openvino environment initialized)
**figure1**
<img width="349" alt="Screenshot 2023-11-30 160859" src="https://github.com/dlstreamer/dlstreamer/assets/105163341/14262563-a24c-4e25-b9e0-899a7fe81d6e">
**figure2**
<img width="415" alt="Screenshot 2023-11-30 160719" src="https://github.com/dlstreamer/dlstreamer/assets/105163341/1a0ba3b8-071c-49a3-b1d6-2dccbcec84a5">

After that, I've installed openvino by selecting "Installing OPENVINO runtime using an archive file" shown in the following figure. Should I choose "Installing OPENVINO using PyPl? Or could you tell me where can I find the full development version to download? Thanks in advance.
<img width="514" alt="Screenshot 2023-11-30 161520" src="https://github.com/dlstreamer/dlstreamer/assets/105163341/18a55906-8103-49dc-86c5-1bd26956b745">

**Comment by akwrobel** [comment]
@henry8248 All of these options install the OpenVINO Toolkit Run time, you can use which ever option you prefer.  
The OpenVINO Toolkit page has a direct download link from the main page here: https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/overview.html

You can find the source on GitHub here: https://github.com/openvinotoolkit/openvino
