### ISSUE TITLE
Proper way to use object-class under gvadetect 

### ISSUE THREAD

**Issue by antoniomtz** [dlstreamer/dlstreamer#434]
Hello,

I'm trying to apply object-class to the yolov8 pipeline as follows:
```
gst-launch-1.0 v4l2src device=/dev/video2 ! decodebin ! gvadetect \
model=/home/dlstreamer/intel/dl_streamer/models/public/yolov8s/FP32/yolov8s.xml \
model-proc=/opt/intel/dlstreamer/samples/gstreamer/model_proc/public/yolo-v8.json \
device=CPU pre-process-backend=ie inference-region=roi-list object_class=person \
! queue ! gvawatermark ! videoconvertscale ! gvafpscounter ! autovideosink sync=false
```

I learned that I need to apply **inference-region=roi-list** in order to make **object_class=person** works, however, I'm not getting any detections of people or any class.

What is the proper way to use inference-region=roi-list object_class=person inside the gvadetect?

**Comment by antoniomtz** [comment]
@brmarkus Thank you for pointing that out. However, the issue still persists with no detection.
Adding `inference-region=roi-list` only gives no detections. 
Can you guide me on how to filter a class using inference-region and object-class attributes on gvadetect?

**Comment by antoniomtz** [comment]
I'm using a the `intel/dlstreamer:latest` tag in a docker environment on Ubuntu 22.04
I haven't changed anything on the `/opt/intel/dlstreamer/samples/gstreamer/model_proc/public/yolo-v8.json` , it is as it comes with the image.

If I remove both `inference-region=roi-list object-class=person` I do see detections of all objects (bounding-boxes). When adding `gvametapublish` I can see the json data with all the inference data in it.

If I add `inference-region=roi-list object-class=person` there is no detections of people  (I'm in front of the camera) and no data from gvametapublish.

**Comment by pmalatyn** [comment]
@brmarkus can you paste content of the model-proc? I would like to understand how labels are defined. 
2nd question did you try provide labels via a separate file?

**Comment by pmalatyn** [comment]
@brmarkus yeah you are right, 
try to use https://dlstreamer.github.io/elements/gvaattachroi.html to generate list of roi (sample: https://github.com/dlstreamer/dlstreamer/tree/master/samples/gstreamer/gst_launch/gvaattachroi) and then rest of the pipeline

**Comment by antoniomtz** [comment]
I tried using `gvaattachroi` before `gvadetect` and I don't get any detections.

This query works fine without `object-class`, I get detections only within the ROI:

`gst-launch-1.0 v4l2src device=/dev/video0 ! decodebin ! gvaattachroi roi=0,0,800,800 ! gvadetect model=/home/dlstreamer/intel/dl_streamer/models/public/yolov8s/FP32/yolov8s.xml model-proc=/opt/intel/dlstreamer/samples/gstreamer/model_proc/public/yolo-v8.json inference-region=1 device=CPU pre-process-backend=ie ! queue ! gvawatermark ! videoconvertscale ! gvafpscounter ! autovideosink sync=false`

When adding `object-class=person` I don't get any detections inside or outside the ROI:

`gst-launch-1.0 v4l2src device=/dev/video0 ! decodebin ! gvaattachroi roi=0,0,800,800 ! gvadetect model=/home/dlstreamer/intel/dl_streamer/models/public/yolov8s/FP32/yolov8s.xml model-proc=/opt/intel/dlstreamer/samples/gstreamer/model_proc/public/yolo-v8.json inference-region=1 object-class=person device=CPU pre-process-backend=ie ! queue ! gvawatermark ! videoconvertscale ! gvafpscounter ! autovideosink sync=false`

**Comment by antoniomtz** [comment]
@pmalatyn @brmarkus any updates on this?

**Comment by pmalatyn** [comment]
@antoniomtz working on it, should have some conclusion by the end of the day

**Comment by pmalatyn** [comment]
this is working pipeline with object-class usage, based on your original one:

gst-launch-1.0 filesrc location=video-examples/People_On_The_Street.mp4 ! qtdemux ! vah264dec ! vapostproc ! video/x-raw\(memory:VAMemory\) ! gvaattachroi mode=1 file-path=roi_list.json ! gvadetect model=/mnt/dlstreamer/dest-dir/dlstreamer3/2022.1.43a3/public/yolov8s/FP32/yolov8s.xml model-proc=samples/gstreamer/model_proc/public/yolo-v8.json inference-region=1 device=CPU pre-process-backend=ie object-class=person ! queue ! gvawatermark ! videoconvertscale ! gvafpscounter ! queue ! gvawatermark ! videoconvertscale ! gvafpscounter ! vah264enc ! h264parse ! mp4mux ! filesink location=Output.mp4

Few remarks here:
1)	The object-class parameter for gvadetect element allows to filter its input ROIs to select only these which have label specified in the parameter. Only these ROIs are taken to further inference/detection, the rest is skipped.
2)	To have list of those ROIs we need to add in a pipeline gvaatachroi element with json file which defines ROIs (see file content below) before gvadetect with inference-region=roi-list and object-class defined 
3)	In our example it defines 2 ROIs covering parts of a full video - car and person:
[
    {
        "objects": [
            {
                "detection": {
                    "label": "person"
                },
                "x": 480,
                "y": 0,
                "w": 1440,
                "h": 1080
            },
            {
                "detection": {
                    "label": "car"
                },
                "x": 0,
                "y": 0,
                "w": 480,
                "h": 1080
            }
        ]
    }
]
4)	Then these 2 ROIs (labeled with person and car respectively) are passed to gvadetect with inference-region=roi-list and object-class=person.
5)	Because object-class in gvadetect is set to person, detection is done only on the part with person label defined in gvaatachroi, but please note that all objects are detected in that ROI, plz see example below:

 
![example](https://github.com/user-attachments/assets/4ddc85e7-371b-4da1-9155-8b8cdfb6131f)

**Comment by pmalatyn** [comment]
we will update the description to be more meaningful but it is working as designed
